force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP-{00000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Line_Item__c/Expense_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Line Item</label>
    <nameField>
        <label>Expense Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Line_Item__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipLabel>Expense Line Items</relationshipLabel>
    <relationshipName>Expense_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExpenseAgentCreateAction.cls
public with sharing class ExpenseAgentCreateAction {
    public class Request {
        @InvocableVariable(required=true)
        public String expenseJson;

        @InvocableVariable
        public Id contentDocumentId;
    }

    public class Response {
        @InvocableVariable
        public Id expenseId;

        @InvocableVariable
        public Integer lineItemCount;
    }

    @InvocableMethod(
        label='Create Expense Records From Confirmed JSON'
        description='Creates Expense__c and Expense_Line_Item__c records from the confirmed expense JSON.'
        category='Agentforce'
    )
    public static List<Response> createExpenseRecords(List<Request> requests) {
        List<Response> responses = new List<Response>();
        for (Request request : requests) {
            ExpenseController.ExpenseCreateResponse createResult = ExpenseController.createExpenseRecord(
                request.expenseJson,
                request.contentDocumentId
            );

            Response response = new Response();
            response.expenseId = createResult.expenseId;
            response.lineItemCount = createResult.lineItemCount;
            responses.add(response);
        }

        return responses;
    }
}